### ISSUE TITLE
Resolving computer names on Windows?

### ISSUE THREAD

**Issue by ZzZombo** [TechnitiumSoftware/DnsServer#411]
The server runs on my Windows 10 machine, its IP address is set for use as the DNS server on my router. I'd like for maximum flexibility to let it also resolve computer names for non-Windows devices such as smartphones, because they access some resources on them, and I'd like not to rely on IP addresses for that. However, it doesn't appear to be the case currently for the DNS server, it doesn't even resolve "DNS Server Domain" under Settings ⇒ General, even though just that would already partially fulfill my request. I have DNSCrypt-proxy in use as the forwarder, but it doesn't appear to handle computer names either but (I get it's out of scope technically for the repo, but any way to handle that on that side would also answer my question).

I do not want to manually map computer names to IPs, the server itself should first check if a domain is a computer name, and if it is, then return it's IP address(es) as appropriate just like the OS does, or something like, the point is to mimic computer name resolution done by Windows.

**Comment by ShreyasZare** [comment]
The problem is not with the DNS server but with the clients. A client will only query the DNS server if it sees a domain name which has a period `.` in it. So, plain computer names wont be attempted by the clients to resolve via the DNS server.

What you need here is to configure your DHCP server with a domain name which will act as a suffix for all your clients on the network. So if you configure a domain name `home` in your DHCP server's config then a client names `abc` will configure itself with `abc.home` as its name which can then be resolved via DNS.

If you router's DHCP server supports configuring the domain name then just configure it there and create a conditional forwarder zone in the DNS server for `home` which forwards to your router's IP address. This will allow the DNS server to resolve all names under the `home` zone via your router.

If your router's DHCP server does not support such a feature then you can disable the DHCP server in your router and configure the built-in DHCP server in Technitium DNS Server. With the built-in DHCP server, the `home` zone will be automatically created and updated internally by the DHCP server.

**Comment by ZzZombo** [comment]
Thanks! I tried to follow your recommendations, but I don't think they work for me. My router does have settings for domain name (set to `Home` by default), so going by them, I would be able to query `mypc.home` using the DNS client in the web UI with the resolver being set to my router's LAN IP address, but it doesn't get resolved successfully, although I can resolve real domains like `github.com` successfully, so the DNS resolver of the router works. Weirder still, I can see my computer hostnames in the list of all connected DHCP clients in the router's UI, so it does know them. I tried to switch over to the built-in DHCP server in Technitium DNS Server instead, but I don't actually understand how to make it used in place of the router's. The router can be used as a DHCP relay, but if configured this way I get Windows complaining it couldn't connect to the DHCP server.

**Comment by ShreyasZare** [comment]
If your router is not resolving `mypc.home` for your device then there is some issue with it. Better way will be to use the built-in DHCP server with Technitium which works well.

You can run only one DHCP server on your network. So, you need to disable your router's DHCP server and enable the Technitium's built in DHCP server by enabling one of the scopes after you configure it. You do not need to configure DHCP relay, since this is something for entirely different use case where you have multiple LAN networks and you want to use just one central DHCP server for all of them.

Make sure that the firewall on the server running Technitium DNS allows incoming udp port 67 requests too for the DHCP to work. Also ensure that the server has a statically configure IP address since that is a requirement to run DHCP server.

In Technitium DHCP, there is already a default scope that you can edit. Just put in the same IP range you had on your router's DHCP. Use your router's IP address as the "Router Address" and make sure that the "DNS Servers" contain the IP address of the your server. Set the "Domain Name" option to `home` which will automatically create a `home` primary zone in the DNS server. Add an exclusion range to exclude first 10 IP addresses in your scope in case you want to manually assign any device a specific IP address so that the DHCP server wont use that range. Save and enable the scope and you are all set.

**Comment by ZzZombo** [comment]
OK so:

* I've enabled the scope (missed this one initially).
* Disabled the DHCP server.
* Connected a device to the LAN.

There is now `android-7d6adcf2af06bd2e` lease with the corresponding `android-7d6adcf2af06bd2e.local` hostname listed. But it absolutely doesn't get resolved when queried via the DNS client:

```json
{
  "Metadata": {
    "NameServer": "mypc (127.0.0.1)",
    "Protocol": "Udp",
    "DatagramSize": "59 bytes",
    "RoundTripTime": "1,14 ms"
  },
  "EDNS": {
    "UdpPayloadSize": 1232,
    "ExtendedRCODE": "NxDomain",
    "Version": 0,
    "Flags": "None",
    "Options": []
  },
  "DnsClientExtendedErrors": [],
  "Identifier": 17708,
  "IsResponse": true,
  "OPCODE": "StandardQuery",
  "AuthoritativeAnswer": false,
  "Truncation": false,
  "RecursionDesired": true,
  "RecursionAvailable": true,
  "Z": 0,
  "AuthenticData": false,
  "CheckingDisabled": false,
  "RCODE": "NxDomain",
  "QDCOUNT": 1,
  "ANCOUNT": 0,
  "NSCOUNT": 0,
  "ARCOUNT": 1,
  "Question": [
    {
      "Name": "android-7d6adcf2af06bd2e.local",
      "Type": "A",
      "Class": "IN"
    }
  ],
  "Answer": [],
  "Authority": [],
  "Additional": [
    {
      "Name": "",
      "Type": "OPT",
      "Class": 1232,
      "TTL": "0 (0 sec)",
      "RDLENGTH": "0 bytes",
      "RDATA": {
        "Options": []
      },
      "DnssecStatus": "Disabled"
    }
  ]
}```

What gives? Any other computer name does not resolve as well, but this one is even listed on the DHCP page so I'd expect it to work.

**Comment by ZzZombo** [comment]
I retract my previous comment. I forgot I had a disabled `local` zone I've been messing around with when I first started to use the software.

However, there is a concern that in the event of the computer being offline, nobody on my network will be able to access Internet. Is there any way to make the router a fallback DHCP server in this case?

**Comment by ZzZombo** [comment]
Thanks for helping me out. However, I think I took this endeavor on a false premise:

> The problem is not with the DNS server but with the clients. **A client will only query the DNS server if it sees a domain name which has a period** in it. So, plain computer names wont be attempted by the clients to resolve via the DNS server. Instead, the client will use mDNS, LLMNR, or NetBIOS name resolution over LAN.

But I just realized that when I configured my another (Android) device to access a webserver over simply `mypc:8080`, it worked as long as I had set a domain zone in TDNS (may I in the future refer to the software as such for brevity?) for it. Also, digging into the gory details further, I figured what I want is TDNS to perform mDNS or similar lookups on my system which apparently there is no support for now rather than to utilize a new DNS zone for local devices, especially because it's still not fully automatic as machines with statically assigned IP addresses aren't assigned a domain name as you know.

As it stands, currently I also can't access my router by it's host name as well, I have to use it's IP address while TDNS is in use, which is sad, but when I used the router's DNS server (or rather, let it use ISP's ones), I could access it; however, it actually doesn't resolve any of the local host names itself as I've already said, it uses a different mechanism that I'd like TDNS to utilize as well.

**Comment by ShreyasZare** [comment]
> Thanks for helping me out. However, I think I took this endeavor on a false premise:

You're welcome.

> But I just realized that when I configured my another (Android) device to access a webserver over simply `mypc:8080`, it worked as long as I had set a domain zone in TDNS (may I in the future refer to the software as such for brevity?) for it. Also, digging into the gory details further, I figured what I want is TDNS to perform mDNS or similar lookups on my system which apparently there is no support for now rather than to utilize a new DNS zone for local devices, especially because it's still not fully automatic as machines with statically assigned IP addresses aren't assigned a domain name as you know.

Accessing `mypc:8080` worked in your case since you got a domain name configured in your DHCP scope, the client will automatically try `mypc.home:8080` and also try `mypc.local:8080` over mDNS.

You can avoid assigning static IP addresses to clients. Static IP is not really required when you can access all devices by its domain name. In specific cases when you require the IP to be static, just convert the dynamic lease for that device to a reserved lease and it will always get the same IP assigned.

> As it stands, currently I also can't access my router by it's host name as well, I have to use it's IP address while TDNS is in use, which is sad, but when I used the router's DNS server (or rather, let it use ISP's ones), I could access it; however, it actually doesn't resolve any of the local host names itself as I've already said, it uses a different mechanism that I'd like TDNS to utilize as well.

Just use the complete domain name like `router.home` and it will always work. Also since the router's IP is static, you will have to make a manual entry in the zone. 

Just using the host name will make the client perform a lot of different local name resolutions first which will take time to resolve. Recommended way is to use the full domain name for accessing all clients.

**Comment by ZzZombo** [comment]
OK, I've tinkered with my setup more based on your input. Actually, the only missing piece that didn't work and thus caused me to create this issue is that the Android device is incapable of resolving `mypc` or `mypc.local` when configured as a proxy in WiFi settings, unless the DNS server responds with a valid IP address. It works OK afterwards even if no DNS record exists for my LAN devices, I can access them just fine anyway. So, on the side of TDNS, I think is needed to resolve the configured "DNS Server Domain" to its IP address. What does that even do anyway? The description reads "The primary fully qualified domain name used by this DNS Server to identify itself" but in what context if not in DNS queries? Evidently neither `mypc` or `mypc.local` are resolvable through TDNS on its own w/o further configuration.

**Comment by ShreyasZare** [comment]
> OK, I've tinkered with my setup more based on your input. Actually, the only missing piece that didn't work and thus caused me to create this issue is that the Android device is incapable of resolving `mypc` or `mypc.local` when configured as a proxy in WiFi settings, unless the DNS server responds with a valid IP address. It works OK afterwards even if no DNS record exists for my LAN devices, I can access them just fine anyway. So, on the side of TDNS, I think is needed to resolve the configured "DNS Server Domain" to its IP address. What does that even do anyway? The description reads "The primary fully qualified domain name used by this DNS Server to identify itself" but in what context if not in DNS queries? Evidently neither `mypc` or `mypc.local` are resolvable through TDNS on its own w/o further configuration.

At this point I think you are either over thinking or confused since this setup really works out of the box with just a few setting changes for the DHCP scope. In the process of getting it to work, it seems either a lot of settings have been randomly changed or that you are not testing the setup correctly.

Also, I am not sure why you are configuring the proxy settings in WiFi. What is the purpose of having a proxy here?

I would suggest that you share screenshots of your zone records, DHCP leases, and DHCP scope so that I can help with the correct config. You can share it over email if you are not comfortable to post it here.

**Comment by ZzZombo** [comment]
Ah, sorry, I reverted back to not using TDNS DHCP server in favor of having the router do that.

> Also, I am not sure why you are configuring the proxy settings in WiFi. What is the purpose of having a proxy here?

Sorry, what kind of question is this? I need it and it all what matters. And if I input a domain name, not an IP address in the "Proxy" field in Settings ⇒ WiFi, it must be resolvable through DNS or it will not work.

So overall the setup is as follows:

* Local network with a router running a DHCP server, and statically assigned IP address for the `mypc` machine.
* Windows 10 running TDNS, set as the DHCP server's DNS server, with a local `dnscrypt-proxy` instance as a DoH forwarder, AKA `mypc`; there is also a HTTP proxy server.
* A different Windows 10 machine.
* Several Android devices.
* All devices other than `mypc` connect to Internet through the proxy running on the latter.

Ultimately I'd like to go away from having any static IPs assigned to any of the devices, and refer to them strictly by assigned names like `mypc`/`mypc.local` or whatever. Using the TDNS DHCP server, however, you still need to keep `mypc` a static IP address for the server to even start so I quit doing that.

**Comment by ShreyasZare** [comment]
> Ah, sorry, I reverted back to not using TDNS DHCP server in favor of having the router do that.
> 
> > Also, I am not sure why you are configuring the proxy settings in WiFi. What is the purpose of having a proxy here?
> 
> Sorry, what kind of question is this? I need it and it is all what matters. And if I input a domain name, not an IP address in the "Proxy" field in Settings ⇒ WiFi, it must be resolvable through DNS or it will not work.

Yes, the domain you enter in the proxy settings will resolve via the DNS but, when the other apps try to use the internet it wont use the DNS instead the HTTP/HTTPS requests will directly go to the HTTP Proxy server which does the domain name resolution. So, if the HTTP proxy server is not on your local network then your devices wont be able to use your local DNS. 

If the HTTP proxy server is hosted locally then the server running the HTTP proxy must be configured to use the local DNS.

This may explain why your android devices are unable to resolve the local domain names.

>   * Windows 10 running TDNS, set as the DHCP server's DNS server, with a local `dnscrypt-proxy` instance as a DoH forwarder, AKA `mypc`; there is also a HTTP proxy server.

You do not need anything else for DoH forwarding since Technitium DNS has built-in support for DoH forwarding.
 
> Ultimately I'd like to go away from having any static IPs assigned to any of the devices, and refer to them strictly by assigned names like `mypc`/`mypc.local` or whatever. 

With the domain name config in your DHCP server you will achieve this.

> Using the TDNS DHCP server, however, you still need to keep `mypc` a static IP address for the server to even start so I quit doing that.

You will need to configure static IP for devices like router, DNS server, and DHCP server since this is mandatory requirement for the network to work and so will need a manual DNS A record entry for them. Apart from that all your devices can get dynamic IP and domain name assigned via DHCP so that you can access all of them using just the domain name (not host name).

**Comment by ZzZombo** [comment]
> This may explain why your android devices are unable to resolve the local domain names.

Sorry, you got it wrong. They do resolve them just fine generally. The only place where this doesn't work is if a local domain is input as the proxy server address to use in a WiFi connection, I suppose mDNS or whatever isn't available where for some reason, so the DNS server should resolve at least the proxy server's domain name for overall WiFi connectivity as otherwise the proxy server is unusable and no HTTP connection can be made. It would suffice if TDNS would resolve its own local name as the proxy resides on the same machine, thus letting me to get away from static IP addresses everywhere.

My question about

> ..."DNS Server Domain"... What does that even do anyway?

still stands, by the way.

**Comment by ShreyasZare** [comment]
> > This may explain why your android devices are unable to resolve the local domain names.
> 
> Sorry, you got it wrong. They do resolve them just fine generally. The only place where this doesn't work is if a local domain is input as the proxy server address to use in a WiFi connection, I suppose mDNS or whatever isn't available where for some reason, so the DNS server should resolve at least the proxy server's domain name for overall WiFi connectivity as otherwise the proxy server is unusable and no HTTP connection can be made. It would suffice if TDNS would resolve its own local name as the proxy resides on the same machine, thus letting me to get away from static IP addresses everywhere.

There is no issue with the DNS server. You can test if the domain resolves using nslookup command or the DNS Client tool in the web console.

> My question about
> 
> > ..."DNS Server Domain"... What does that even do anyway?
> 
> still stands, by the way.

The "DNS Server Domain" is the domain name that the DNS server must use when creating new zones for use as the primary name server in the SOA record. That domain name is not going to resolve by its own. You need to create a zone for it and add an A record entry. This domain name has nothing to do with general resolution functions.

**Comment by ZzZombo** [comment]
> There is no issue with the DNS server.

Oh forgive me, I didn't want to leave an impression there is! From the very start it was more of a discussion and a bit of a feature request mixed in. The request is to make TDNS aware of _its own local name_ to resolve to its IP address. The discussion was about how can I achieve my goal in absence of such a function.

**Comment by ShreyasZare** [comment]
> > There is no issue with the DNS server.
> 
> Oh forgive me, I didn't want to leave an impression there is! From the very start it was more of a discussion and a bit of a feature request mixed in. The request is to make TDNS aware of _its own local name_ to resolve to its IP address. The discussion was about how can I achieve my goal in absence of such a function.

What I am trying to explain is that the DNS server cannot resolve host names since the clients wont ask it in the first place. It also cannot resolve its own name given in the "DNS Server Domain" since the DNS server cannot figure out on its own which IP address to return for it. You need to have a zone to resolve the server's domain name. Again, if this domain name is just a host name then its not going to work since the client wont query the DNS server for host names.

You need to configure your clients with correct domain that you have setup with the DHCP server. Do not think that mDNS or other such protocols will resolve it since they are only used for resolving host names. When you give a full domain name, the client is going to resolve it using the DNS server.
