### ISSUE TITLE
In DHCP leases, rename "Host Name"

### ISSUE THREAD

**Issue by Matthew-Bonner** [TechnitiumSoftware/DnsServer#63]
The term 

> Host Name

 is misleading as it is user input to label the lease, I think it would be better being renamed to "Comment" or "Label".

![image](https://user-images.githubusercontent.com/7858744/61493975-dbe1fb00-a9ac-11e9-8ca4-e6ee0e544ed1.png)

I also think the order should be:

- IP Address
- MAC Address
- Comment

As this makes even more sense.

**Comment by ShreyasZare** [comment]
Thanks for the feedback. 

Host Name is correct term for this item which is actually optional. The device's host name gets updated automatically to this field overwriting any existing name when the DHCP server assigns the reserved IP address. Main purpose of the field is to allow identifying the device easily while updating the settings.

I think it would be much clear if that field is marked optional.

**Comment by Matthew-Bonner** [comment]
But the device already has its own host name so is there a reason to do this? Most other implementations just use the device host name or have it blank if one is not being broadcast. I think it would be better if this was just a comment or label. If someone wants to override a host name, they have DNS for that, or am I mistaking something?

**Comment by ShreyasZare** [comment]
The field is really the device's own host name which device is sending in the request to DHCP server. The host name from the request is updated to the reserved leases list overwriting any existing name. It cannot be comment or label as it gets overwritten with the latest host name of the device automatically.

While configuring the reserved lease option, the host name field is optional. Its just there to allow you to identify the device while adding or removing entries. So, you can add a host name while adding the MAC address for clarity while you review all entries. If you kept it empty and later check back after the device was assigned reserved lease then you will see the device's host name updated in there.

The host name field is not really required and was added only in later implementation stages to allow you to help manage the reserved lease list. If device name updates then it will reflect there. So, you dont need to check the MAC address to find out which device it is which is really useful when your list is huge.

Host name provided by the device will be used to update the DNS forward and reverse lookup. So, the host name in there will have an exact domain name available.

**Comment by Matthew-Bonner** [comment]
> The field is really the device's own host name which device is sending in the request to DHCP server.

In my case the field was blank, and I had to populate it.

> It cannot be comment or label as it gets overwritten with the latest host name of the device automatically.

I would consider this unexpected behaviour, other people may also consider this unexpected too, I would suspect if you left the implementation as is you'll find a lot of people logging bugs. It is never a good idea to overwrite user input with a computer generated value unexpectedly.

> If you kept it empty and later check back after the device was assigned reserved lease then you will see the device's host name updated in there.

I will give this a try as so far I've manually been populating it.

My router has an ARP table with an additional column in the table to show the hostname being broadcast and the devices which had a blank hostname in the dashboard had a hostname in the ARP table.

> While configuring the reserved lease option, the host name field is optional. Its just there to allow you to identify the device while adding or removing entries.

This is exactly my point, it is more so a comment than it is anything else.

My router shows it as a comment too like so:
![image](https://user-images.githubusercontent.com/7858744/61530702-bb518980-aa1c-11e9-93a1-1ede3c0355a7.png)

> If device name updates then it will reflect there. So, you dont need to check the MAC address to find out which device it is which is really useful when your list is huge.

But if it is a comment the user input, it then doesn't need to be updated.

**Comment by ShreyasZare** [comment]
> In my case the field was blank, and I had to populate it.

It gets populated after the device requests for lease. If its still blank then it may be that the device didnt send host name option in request which is a bit odd since most devices are expected to send that option.

> My router has an ARP table with an additional column in the table to show the hostname being broadcast and the devices which had a blank hostname in the dashboard had a hostname in the ARP table.

Here the hostname displayed by ARP table must have been resolved by broadcast name resolution methods which the DHCP server is not using.

> But if it is a comment the user input, it then doesn't need to be updated.

Fair point. Its making the input field difficult to understand. I think just displaying the host name as a simple text in a column after MAC address & IP address would make more sense and help in identifying the device as originally intended.

**Comment by Matthew-Bonner** [comment]
> Fair point. Its making the input field difficult to understand. I think just displaying the host name as a simple text in a column after MAC address & IP address would make more sense and help in identifying the device as originally intended.

I agree, but could we still have a comment field as a back up option in case it is blank?

**Comment by ShreyasZare** [comment]
We can have comment field if its useful. I just have a feeling that most people would not use it.

**Comment by Matthew-Bonner** [comment]
I would definitely prefer a comment field, I have multiple devices showing up in the list with hostnames similar to:

android-abccfa76d54a83f2

I would never remember which is which, so by adding a comment, I can at least know which is mobile it is I'm working with.

**Comment by ShreyasZare** [comment]
Right, so I will add comment field and make the existing host name view-only.

**Comment by Matthew-Bonner** [comment]
Do you want me to make this change and send a PR? Happy to do so.

**Comment by ShreyasZare** [comment]
> Do you want me to make this change and send a PR? Happy to do so.

Thanks for the offer but, its almost done here.

**Comment by Matthew-Bonner** [comment]
If you want me to pick up any of the other changes feel free to let me know, saves you doing all the work yourself as I know I've been requesting quite a lot and feel bad not lending a helping hand.

**Comment by ShreyasZare** [comment]
Technitium DNS Server v4.1 is now available that fixes this issue.
